#server.port=8084
#spring.application.name=zuul-server
#eureka.instance.preferIpAddress=true
#eureka.client.registerWithEureka=true
#eureka.client.fetchRegistry=true
#eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
#zuul.sensitiveHeaders= Cookie,Set-Cookie
#zuul.ignored-headers= Access-Control-Allow-Credentials, Access-Control-Allow-Origin
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: '7777'
eureka:
  client:
    enabled: true
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: '30'
